version: '3.5'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    volumes:
      - ./backend:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    command: /bin/sh -c "cargo watch -x run"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: /bin/sh -c "npm ci && npm run dev"

volumes:
  cargo-cache: null
  target-cache: null
  node_modules: null
